import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "welcomeText": "Welcome to Healthify.",
          "realTimePrediction":
              "Get real-time prediction of a heart stroke using machine learning and fitness trackers.",
          "realTimeAlerts": "Real-time alerts",
          "healthy": "Stay Healthy",
          "exploring": "Explore the app",
          "linkAccount":
              "Link your Google Fit/ Mi Fit account and start receiving real-time analytics and predictions.",
          "heartTips":
              "Get latest news, and health tips to keep your heart safe.",
          "heartInfo":
              "Get detailed analytics of your daily activity and heart related information. ",
          "clickStartBtn": "Click on Get Started",
          "startedBtn": "Get Started",
          "skipBtn": "Skip",
          "nextBtn": "Next",
          "languageBtn_english": "English",
          "languageBtn_hindi": "Hindi",
          "languageBtn_telugu": "Telugu",
          "languageBtn_gujarati": "Gujarati",
          "languageBtn_marathi": "Marathi",
          "healthify": "Healthify",
          "whichOne": "Which one are you?",
          "signIn": "Sign In",
          "signUp": "Sign Up",
          "female": "Female",
          "fullName": "Full Name",
          "aboutYourSelf": "Tell us about yourself",
          "email": "Email",
          "male": "Male",
          "password": "Password",
          "height": "Height",
          "centimeter": "centm",
          "provide": "Please provide your",
          "cancel": "Cancel",
          "done": "Done",
          "kilograms": "kg",
          "emergency": "Emergency contacts:",
          "shareContact":
              " Share the contact number of the people you want to list as your",
          "birthdy": "Birthday",
          "forgetPassword": "Forget Password? ",
          "contact": "Contact",
          "weight": "Weight",
          "walking": "Walking",
          "register": "Don’t have an account?   Register",
          "loginIfHaveAccount": "Already have an account?   Sign In",
          "next": "Next",
          "hello": "Hello",
          "increasedHeartRate": "Increased Heart rate. Are you okay?",
          "daysAgo": " days ago",
          "heartRate": "Heart Rate",
          "exercise": "Exercise",
          "ExperiencingHeartStroke": "Experiencing a Heart Stroke?",
          "bpm": "bpm",
          "min": "min",
          "yes": "YES",
          "no": "NO",
          "sleep": "Sleep",
          "calories": " Calories",
          " kcal": " kCal",
          "tips": "Tips for a Healthy heart",
          "suddenHeartStroke":
              "Here’s what to do incase of a sudden Heart Stroke",
          "name": "Mistry Pavan Kumar",
          "panBong": "Pan Bong",
          "analytics": "Analytics",
          "bodyMass": "Body Mass Index",
          "weight": "You have a normal weight",
          "viewMore": "View More",
          "tracker": "heart rate tracker",
          "weekly": "weekly",
          "bodyWorkout": "upper body workout",
          "sunday": "sun",
          "monday": "mon",
          "tuesday": "tue",
          "wednesday": "wed",
          "thursday": "thurs",
          "friday": "fri",
          "saturday": "sat",
          "countSteps": "steps count",
          "updates": "updates",
          "stacked": "Stacked Column from Syncfusion",
          "calories": "Calories",
          "activityProgress": "activityProgress",
          "weekly": "weekly",
          "stroke": "Having a Stroke?",
          "alert": "An alert has been sent to your emergency contact",
          "callAmb": "Call an Ambulance",
          "whatToDo": "What to do?",
          "waitAmb":
              "Stay Calm, and wait for Ambulance. Do not panic. If you have called an ambulance, wait for help to arrive. Do not attempt to drive.",
          "stayAwake":
              "Do not lose conciousnessTry to stay awake. If you believe you are losing consciousness, take an aspirin. Try keeping your eyes open.",
          "cpr":
              "Importance of CPRIf you are not alone and there is someone to assist you, ask them to perform CPR if your vitals are dropping.",
          "symprtoms":
              "Check for Symprtoms: Face: If your face is drooping. ,Arm: If your arms feel weak.,Speech: Speech difficulties. Then it is,Time to call an Ambulance",
          "notification": "Notification",
          "noMove": "You haven’t moved since one hour",
          "dailyWork": "Your daily reminder to work out",
          "waterBreak": "Hey, it’s time for a water break",
          "locShared":
              "SOS! Your location has been shared to your Emergency contanct.",
          "profile": "Profile",
          "edit": "Edit",
          "name": "Sai Kamal",
          "save": "Save",
          "height": "Height",
          "weight": "Weight",
          "age": "Age",
          "account": "Account",
          "data": "Personal Data",
          "contacts": "Emergency Contacts",
          "history": "Activity History",
          "remainders": "Set remainders",
          "preferences": "",
          "notification": "Preferences",
          "language": "Notification",
          "languages": "Languages",
          "other": "Other",
          "contactUs": "Contact Us",
          "privacy": "Privacy Policy",
          "news": "News",
          "tips": "Tips for having",
          "healthyHeart": "healthy heart",
          "name": "Pavan Kumar",
          "mints": "mints read",
          "solution":
              "Our proposed solution is a mobile app that predicts the risk of heart strokes using ML and data collected from fitness trackers. The app will provide users with personalized recommendations to reduce their risk of heart strokes based on the data analysis.",
        },
        'hi_IN': {
          "welcomeText": "हेल्थीफाई में आपका स्वागत है।",
          "realTimePrediction":
              "मशीन लर्निंग और फिटनेस ट्रैकर का उपयोग करके हृदय स्ट्रोक का वास्तविक समय भविष्यवाणी प्राप्त करें।",
          "realTimeAlerts": "वास्तविक समय चेतावनियां",
          "healthy": "स्वस्थ रहें",
          "exploring": "ऐप खोजें",
          "linkAccount":
              "अपने Google Fit / Mi Fit खाते को लिंक करें और वास्तविक समय विश्लेषण और भविष्यवाणियां प्राप्त करना शुरू करें।",
          "heartTips":
              "अपने हृदय को सुरक्षित रखने के लिए नवीनतम समाचार और स्वास्थ्य युक्तियां प्राप्त करें।",
          "heartInfo":
              "अपनी दैनिक गतिविधि और हृदय संबंधी जानकारी का विस्तृत विश्लेषण प्राप्त करें।",
          "clickStartBtn": "जारी रखने के लिए शुरू करने पर क्लिक करें",
          "startedBtn": "शुरू करें",
          "skipBtn": "छोड",
          "nextBtn": "अगला",
          "languageBtn_english": "अंग्रेज़ी",
          "languageBtn_hindi": "हिन्दी",
          "languageBtn_telugu": "तेलुगू",
          "languageBtn_gujarati": "गुजराती",
          "languageBtn_marathi": "मराठी",
          "healthify": "स्वस्थ",
          "whichOne": "जो एक आप हैं?",
          "signIn": "दाखिल करना",
          "signUp": "साइन अप करें",
          "female": "महिला",
          "fullName": "पूरा नाम",
          "aboutYourSelf": "अपने बारे में हमें बताएं",
          "email": "ईमेल",
          "male": "नर",
          "password": "पासवर्ड",
          "height": "ऊंचाई",
          "centimeter": "सें.मी",
          "provide": "कृपया अपना प्रदान करें,",
          "cancel": "रद्द करना",
          "done": "पूर्ण",
          "kilograms": "किग्रा",
          "walking": "टहलना",
          "emergency": "आपातकालीन संपर्क:",
          "shareContact":
              "उन लोगों का संपर्क नंबर साझा करें जिन्हें आप अपने आपातकालीन संपर्क के रूप में सूचीबद्ध करना चाहते हैं",
          "birthdy": "जन्मदिन",
          "forgetPassword": " पासवर्ड भूल गए?",
          "contact": "संपर्क",
          "weight": "वज़न",
          "register": "खाता नहीं है? पंजीकरण करवाना",
          "loginIfHaveAccount":
              "क्या आपके पास पहले से एक खाता मौजूद है? दाखिल करना",
          "next": "वज़न",
          "hello": "नमस्ते",
          "increasedHeartRate": "बढ़ी हृदय की दर। आप ठीक है न?",
          "daysAgo": "दिन पहले",
          "heartRate": "हृदय दर",
          "exercise": "व्यायाम",
          "ExperiencingHeartStroke": "दिल का दौरा पड़ रहा है?",
          "bpm": "बीपीएम",
          "min": "मिन",
          "yes": "हाँ",
          "no": "नहीं",
          "sleep": "नींद",
          "calories": "कैलोरी",
          " kcal": "किलो कैलोरी",
          "tips": "स्वस्थ दिल के लिए टिप्स यहाँ क्या करना है",
          "suddenHeartStroke": "अचानक दिल का दौरा",
          "name": "मिस्त्री पवन कुमार",
          "panBong": "पैन बोंग",
          "analytics": "एनालिटिक्स",
          "bodyMass": "बीएमआई (बॉडी मास इंडेक्स)",
          "weight": "आपका वजन सामान्य है",
          "viewMore": "और देखें",
          "tracker": "हृदय गति ट्रैकर",
          "weekly": "साप्ताहिक",
          "bodyWorkout": "अपरबॉडी वर्कआउट",
          "sunday": "रवि",
          "monday": "सोमवार",
          "tuesday": "मंगल",
          "wednesday": "बुध",
          "thursday": "गुरु",
          "friday": "शुक्र",
          "saturday": "बैठा",
          "countSteps": "कदम गिनते हैं",
          "sleep": "नींद",
          "updates": "वास्तविक समय अद्यतन",
          "stacked": "स्टैक्ड कॉलम",
          "calories": "कैलोरी",
          "activityProgress": "गतिविधि प्रगति",
          "weekly": "साप्ताहिक",
          "stroke": "स्ट्रोक हो रहा है?",
          "alert": "आपके आपातकालीन संपर्क को अलर्ट भेज दिया गया है",
          "callAmb": "ऐम्बुलेंस बुलाएं",
          "whatToDo": "क्या करें?",
          "waitAmb":
              "शांत रहें और एम्बुलेंस की प्रतीक्षा करें। घबड़ाएं नहीं। अगर आपने एंबुलेंस को कॉल किया है, तो मदद के आने का इंतजार करें। चलाने का प्रयास न करें।",
          "stayAwake":
              "होश मत खोना जागते रहने की कोशिश करें। अगर आपको लगता है कि आप होश खो रहे हैं, तो एस्पिरिन लें। अपनी आंखें खुली रखने का प्रयास करें।",
          "cpr":
              "सीपीआर का महत्व यदि आप अकेले नहीं हैं और आपकी सहायता के लिए कोई है, तो उन्हें सीपीआर करने के लिए कहें यदि आपके विटल्स कम हो रहे हैं।",
          "symprtoms":
              "लक्षणों की जांच करें: चेहरा: अगर आपका चेहरा लटक रहा है। भुजा: यदि आपकी बाहें कमजोर महसूस करती हैं। भाषण: भाषण कठिनाइयों। तो यह एम्बुलेंस को कॉल करने का समय है",
          "notification": "अधिसूचना",
          "noMove": "आप एक घंटे से कहीं नहीं गए हैं",
          "dailyWork": "वर्कआउट करने के लिए आपका दैनिक रिमाइंडर",
          "waterBreak": "अरे, यह पानी के ब्रेक का समय है",
          "locShared":
              "मुसीबत का इशारा! आपका स्थान आपके आपातकालीन संपर्क से साझा कर दिया गया है।",
          "profile": "प्रोफ़ाइल",
          "edit": "संपादन करना",
          "name": "साईं कमल",
          "save": "बचाना",
          "height": "ऊंचाई",
          "weight": "वज़न",
          "age": "आयु",
          "account": "खाता",
          "data": "व्यक्तिगत डेटा",
          "contacts": "आपातकालीन संपर्क",
          "history": "गतिविधि इतिहास",
          "remainders": "अवशेष सेट करें",
          "preferences": "पसंद",
          "notification": "अधिसूचना",
          "language": "भाषा",
          "languages": "अंग्रेज़ी",
          "other": "अन्य",
          "contactUs": "संपर्क करें",
          "privacy": "गोपनीयता नीति",
          "news": "समाचार",
          "tips": "होने के टिप्स",
          "healthyHeart": "स्वस्थ दिल",
          "name": "एम. पवन कुमार",
          "mints": "मिनट पढ़ा",
          "solution":
              "हमारा प्रस्तावित समाधान एक मोबाइल ऐप है जो एमएल और फिटनेस ट्रैकर्स से एकत्र किए गए डेटा का उपयोग करके दिल के दौरे के जोखिम की भविष्यवाणी करता है। ऐप उपयोगकर्ताओं को डेटा विश्लेषण के आधार पर दिल के दौरे के जोखिम को कम करने के लिए व्यक्तिगत सिफारिशें प्रदान करेगा।",
        },
        "ta_IN": {
          "welcomeText": "Healthifyக்கு வரவேற்கிறோம்.",
          "realTimePrediction":
              "மெஷின் லேர்னிங் மற்றும் ஃபிட்னஸ் டிராக்கர்களைப் பயன்படுத்தி மாரடைப்புக்கான நிகழ்நேரக் கணிப்புகளைப் பெறுங்கள்.",
          "realTimeAlerts": "நிகழ் நேர விழிப்பூட்டல்கள்",
          "healthy": "ஆரோக்கியமாக இரு",
          "exploring": "பயன்பாட்டை ஆராயுங்கள்",
          "linkAccount":
              "உங்கள் Google Fit/ Mi Fit கணக்கை இணைத்து, நிகழ்நேர பகுப்பாய்வு மற்றும் கணிப்புகளைப் பெறத் தொடங்குங்கள்.",
          "heartTips":
              "உங்கள் இதயத்தைப் பாதுகாப்பாக வைத்திருக்க சமீபத்திய செய்திகள் மற்றும் சுகாதார உதவிக்குறிப்புகளைப் பெறுங்கள்.",
          "heartInfo":
              "உங்கள் தினசரி செயல்பாடு மற்றும் இதயம் தொடர்பான தகவல்களின் விரிவான பகுப்பாய்வுகளைப் பெறுங்கள்.",
          "clickStartBtn": "தொடர தொடங்கு என்பதைக் கிளிக் செய்யவும்",
          "startedBtn": "தொடங்குங்கள்",
          "skipBtn": "தவிர்க்கவும்",
          "nextBtn": "அடுத்தது",
          "languageBtn_english": "ஆங்கிலம்",
          "languageBtn_hindi": "ஹிந்தி",
          "languageBtn_telugu": "தெலுங்கு",
          "languageBtn_gujarati": "குஜராத்தி",
          "languageBtn_marathi": "மராத்தி",
          "healthify": "ஆரோக்கியமாக்கும்",
          "whichOne": "இதில் நீ யார்?",
          "signIn": "உள்நுழையவும்",
          "signUp": "பதிவு செய்யவும்",
          "female": "பெண்",
          "fullName": "முழு பெயர்",
          "aboutYourSelf": "உங்களைப் பற்றி எங்களிடம் கூறுங்கள்",
          "email": "மின்னஞ்சல்",
          "male": "ஆண்",
          "password": "கடவுச்சொல்",
          "height": "உயரம்",
          "centimeter": "செ.மீ",
          "provide": "தயவுசெய்து உங்கள்",
          "cancel": "ரத்து செய்",
          "done": "முடிந்தது",
          "emergency": "அவசர தொடர்புகள்:",
          "shareContact":
              "உங்கள் அவசரகாலத் தொடர்பு என நீங்கள் பட்டியலிட விரும்பும் நபர்களின் தொடர்பு எண்ணைப் பகிரவும்",
          "birthdy": "பிறந்தநாள்",
          "forgetPassword": " கடவுச்சொல்லை மறந்து?",
          "contact": "தொடர்பு",
          "weight": "எடை",
          "register": "கணக்கு இல்லையா? பதிவு",
          "loginIfHaveAccount": "ஏற்கனவே ஒரு கணக்கு உள்ளதா? உள்நுழையவும்",
          "next": "அடுத்தது",
          "hello": "வணக்கம்,",
          "increasedHeartRate": "அதிகரித்த இதயத் துடிப்பு. நலமா?",
          "daysAgo": "களுக்கு முன்பு",
          "heartRate": "இதய துடிப்பு",
          "exercise": "உடற்பயிற்சி",
          "ExperiencingHeartStroke": "மாரடைப்பு ஏற்படுகிறதா?",
          "bpm": "bpm",
          "min": "நிமிடம்",
          "yes": "ஆம்",
          "no": "இல்லை",
          "sleep": "தூங்கு",
          "calories": "கலோரிகள்",
          " kcal": "kCal",
          "tips": "ஆரோக்கியமான இதயத்திற்கான குறிப்புகள்",
          "suddenHeartStroke":
              "என்ன செய்ய வேண்டும் என்பது இங்கே திடீர் மாரடைப்பு",
          "name": "மிஸ்திரி பவன் குமார்",
          "panBong": "பான் பாங்",
          "analytics": "பகுப்பாய்வு",
          "bodyMass": "பிஎம்ஐ (உடல் நிறை குறியீட்டெண்)",
          "weight": "உங்களுக்கு சாதாரண எடை உள்ளது",
          "viewMore": "மேலும் பார்க்க",
          "tracker": "இதய துடிப்பு கண்காணிப்பான்",
          "weekly": "வாரந்தோறும்",
          "bodyWorkout": "மேல் உடல் பயிற்சி",
          "sunday": "சூரியன்",
          "monday": "திங்கள்",
          "tuesday": "செவ்வாய்",
          "wednesday": "திருமணம் செய்",
          "thursday": "வியாழன்",
          "friday": "வெள்ளி",
          "saturday": "வெள்ளி",
          "countSteps": "படிகள் எண்ணிக்கை",
          "sleep": "தூங்கு",
          "updates": "நிகழ் நேர புதுப்பிப்புகள்",
          "stacked": "அடுக்கப்பட்ட நெடுவரிசை",
          "calories": "கலோரிகள்",
          "activityProgress": "செயல்பாடு முன்னேற்றம்",
          "weekly": "வாரந்தோறும்",
          "stroke": "பக்கவாதம் உள்ளதா?",
          "alert": "உங்கள் அவசரகாலத் தொடர்புக்கு எச்சரிக்கை அனுப்பப்பட்டுள்ளது",
          "callAmb": "ஆம்புலன்ஸை அழைக்கவும்",
          "whatToDo": "என்ன செய்ய?",
          "waitAmb":
              "அமைதியாக இருங்கள், ஆம்புலன்சுக்காக காத்திருங்கள். பீதியடைய வேண்டாம். நீங்கள் ஆம்புலன்ஸை அழைத்திருந்தால், உதவி வரும் வரை காத்திருக்கவும். ஓட்ட முயற்சிக்காதீர்கள்.",
          "stayAwake":
              "சுயநினைவை இழக்காதீர்கள் விழித்திருக்க முயற்சி செய்யுங்கள். நீங்கள் சுயநினைவை இழக்கிறீர்கள் என்று நீங்கள் நம்பினால், ஆஸ்பிரின் எடுத்துக் கொள்ளுங்கள். உங்கள் கண்களைத் திறந்து வைக்க முயற்சிக்கவும்.",
          "cpr":
              "CPR இன் முக்கியத்துவம் நீங்கள் தனியாக இல்லை மற்றும் உங்களுக்கு உதவ யாராவது இருந்தால், உங்கள் உயிர்ச்சக்திகள் குறைந்துவிட்டால், CPR ஐச் செய்யும்படி அவர்களிடம் கேளுங்கள்.",
          "symprtoms":
              "அறிகுறிகளை சரிபார்க்கவும்: முகம்: உங்கள் முகம் சாய்ந்திருந்தால். கை: உங்கள் கைகள் பலவீனமாக உணர்ந்தால். பேச்சு: பேச்சு சிரமங்கள். பின்னர் ஆம்புலன்ஸ் அழைக்க வேண்டிய நேரம் இது",
          "notification": "அறிவிப்பு",
          "noMove": "ஒரு மணி நேரத்திலிருந்து நீங்கள் நகரவில்லை",
          "dailyWork": "வேலை செய்வதற்கான உங்கள் தினசரி நினைவூட்டல்",
          "waterBreak": "ஏய், இது தண்ணீர் இடைவேளைக்கான நேரம்",
          "locShared":
              "SOS! உங்களின் அவசரத் தொடர்புக்கு உங்கள் இருப்பிடம் பகிரப்பட்டது.",
          "profile": "சுயவிவரம்",
          "edit": "தொகு",
          "name": "சாய் கமல்",
          "save": "சேமிக்கவும்",
          "height": "உயரம்",
          "weight": "எடை",
          "age": "வயது",
          "account": "கணக்கு",
          "data": "தனிப்பட்ட தகவல்",
          "contacts": "அவசரத் தொடர்புகள்",
          "history": "செயல்பாட்டு வரலாறு",
          "remainders": "செட் எஞ்சியுள்ளது",
          "preferences": "விருப்பங்கள்",
          "notification": "அறிவிப்பு",
          "language": "மொழி",
          "languages": "ஆங்கிலம்",
          "other": "மற்றவை",
          "contactUs": "எங்களை தொடர்பு கொள்ள",
          "privacy": "தனியுரிமைக் கொள்கை",
          "news": "செய்தி",
          "tips": "வைத்திருப்பதற்கான உதவிக்குறிப்புகள்",
          "healthyHeart": " ஆரோக்கியமான இதயம்",
          "name": " எம். பவன் குமார்",
          "mints": "நிமிடம் படித்தேன் ",
          "solution":
              "எங்களின் முன்மொழியப்பட்ட தீர்வு, ML மற்றும் ஃபிட்னஸ் டிராக்கர்களிடமிருந்து சேகரிக்கப்பட்ட தரவுகளைப் பயன்படுத்தி இதயப் பக்கவாதம் ஏற்படும் அபாயத்தைக் கணிக்கும் மொபைல் செயலியாகும். தரவு பகுப்பாய்வின் அடிப்படையில் மாரடைப்பு அபாயத்தைக் குறைக்க பயனர்களுக்கு தனிப்பயனாக்கப்பட்ட பரிந்துரைகளை ஆப்ஸ் வழங்கும்.",
        },
        'te_IN': {
          "welcomeText": "Healthifyకి స్వాగతం.",
          "realTimePrediction":
              "మెషిన్ లెర్నింగ్ మరియు ఫిట్‌నెస్ ట్రాకర్‌లను ఉపయోగించి హార్ట్ స్ట్రోక్ గురించి నిజ-సమయ అంచనాను పొందండి.",
          "realTimeAlerts": "నిజ-సమయ హెచ్చరికలు",
          "healthy": "ఆరోగ్యంగా ఉండు",
          "exploring": "యాప్‌ను అన్వేషించండి",
          "linkAccount":
              "మీ Google Fit/ Mi Fit ఖాతాను లింక్ చేయండి మరియు నిజ-సమయ విశ్లేషణలు మరియు అంచనాలను స్వీకరించడం ప్రారంభించండి.",
          "heartTips":
              "మీ గుండెను సురక్షితంగా ఉంచుకోవడానికి తాజా వార్తలు మరియు ఆరోగ్య చిట్కాలను పొందండి.",
          "heartInfo":
              "మీ రోజువారీ కార్యాచరణ మరియు గుండె సంబంధిత సమాచారం యొక్క వివరణాత్మక విశ్లేషణలను పొందండి. ",
          "clickStartBtn": "కొనసాగించడానికి ప్రారంభంపై క్లిక్ చేయండి",
          "startedBtn": "ప్రారంభించడానికి",
          "skipBtn": "దాటవేయి",
          "nextBtn": "తరువాత",
          "languageBtn_english": "ఆంగ్ల",
          "languageBtn_hindi": "హిందీ",
          "languageBtn_telugu": "తెలుగు",
          "languageBtn_gujarati": "గుజరాతి",
          "languageBtn_marathi": "మరాఠీ",
          "healthify": "ఆరోగ్యకరం",
          "whichOne": "మీరు ఎవరు?",
          "signIn": "సైన్ ఇన్ చేయండి",
          "signUp": "సైన్ ఇన్ చేయండి",
          "female": "స్త్రీ",
          "fullName": "పూర్తి పేరు",
          "aboutYourSelf": "మీ గురించి చెప్పండి",
          "email": "ఇమెయిల్",
          "male": "పురుషుడు",
          "password": "పాస్వర్డ్",
          "walking": 'వాకింగ్',
          "height": "ఎత్తు",
          "centimeter": "సెం.మీ",
          "provide": "దయచేసి మీ అందించండి,",
          "cancel": "రద్దు చేయండి",
          "done": "పూర్తి",
          "kilograms": "కిలోలు",
          "emergency": "అత్యవసర పరిచయాలు:",
          "shareContact":
              "మీరు మీ ఎమర్జెన్సీ కాంటాక్ట్‌గా లిస్ట్ చేయాలనుకుంటున్న వ్యక్తుల కాంటాక్ట్ నంబర్‌ను షేర్ చేయండి",
          "birthdy": "పుట్టినరోజు",
          "forgetPassword": "పాస్‌వర్డ్ మర్చిపోయారా? ",
          "contact": "సంప్రదింపు",
          "weight": "బరువు",
          "register": "ఖాతా లేదా? నమోదు చేసుకోండి",
          "loginIfHaveAccount": "ఖాతా కలిగి ఉన్నారా? సైన్ ఇన్ చేయండి",
          "next": "తరువాత",
          "hello": "హలో",
          "increasedHeartRate": "పెరిగిన హృదయ స్పందన రేటు. మీరు బాగున్నారా?",
          "daysAgo": "రోజుల క్రితం",
          "heartRate": "గుండెవేగం",
          "exercise": "వ్యాయామం",
          "ExperiencingHeartStroke": "హార్ట్ స్ట్రోక్‌ని ఎదుర్కొంటున్నారా?",
          "bpm": "bpm",
          "min": "నిమి",
          "yes": "అవును",
          "no": "నం",
          "sleep": "నిద్రించు",
          "calories": "కేలరీలు",
          " kcal": "",
          "tips": "ఆరోగ్యకరమైన గుండె కోసం చిట్కాలు",
          "suddenHeartStroke":
              "ఈ సందర్భంలో ఏమి చేయాలో ఇక్కడ ఉంది అకస్మాత్తుగా హార్ట్ స్ట్రోక్",
          "name": "మిస్త్రీ పవన్ కుమార్",
          "panBong": "పాన్ బాంగ్",
          "analytics": "విశ్లేషణలు",
          "bodyMass": "బాడీ మాస్ ఇండెక్స్",
          "weight": "మీకు సాధారణ బరువు ఉంది",
          "viewMore": "మరిన్ని చూడండి",
          "tracker": "హృదయ స్పందన ట్రాకర్",
          "weekly": "వారానికోసారి",
          "bodyWorkout": "ఎగువ శరీర వ్యాయామం",
          "sunday": "సూర్యుడు",
          "monday": "సోమ",
          "tuesday": "మంగళ",
          "wednesday": "బుధ",
          "thursday": "గురువారం",
          "friday": "శుక్ర",
          "saturday": "శని",
          "countSteps": "దశలు లెక్కించబడతాయి",
          "sleep": "నిద్రించు",
          "updates": "రియల్ టైమ్ అప్‌డేట్‌లు",
          "stacked": "పేర్చబడిన కాలమ్",
          "calories": "కేలరీలు",
          "activityProgress": "కార్యాచరణ పురోగతి",
          "weekly": "వారానికోసారి",
          "stroke": "",
          "alert": "",
          "callAmb": "",
          "whatToDo": "",
          "waitAmb":
              "ప్రశాంతంగా ఉండండి మరియు అంబులెన్స్ కోసం వేచి ఉండండి.ఆందోళన పడకండి. మీరు అంబులెన్స్‌కు కాల్ చేసి ఉంటే, సహాయం వచ్చే వరకు వేచి ఉండండి. డ్రైవ్ చేయడానికి ప్రయత్నించవద్దు.",
          "stayAwake":
              "స్పృహ కోల్పోవద్దు మెలకువగా ఉండేందుకు ప్రయత్నించండి. మీరు స్పృహ కోల్పోతున్నారని మీరు విశ్వసిస్తే, ఆస్పిరిన్ తీసుకోండి. మీ కళ్ళు తెరిచి ఉంచడానికి ప్రయత్నించండి.",
          "cpr":
              "CPR యొక్క ప్రాముఖ్యత మీరు ఒంటరిగా లేకుంటే మరియు మీకు సహాయం చేయడానికి ఎవరైనా ఉంటే, మీ ప్రాణాధారాలు తగ్గుతున్నట్లయితే CPR చేయమని వారిని అడగండి.",
          "symprtoms":
              "లక్షణాల కోసం తనిఖీ చేయండి: ముఖం: మీ ముఖం వంగిపోయి ఉంటే. చేయి: మీ చేతులు బలహీనంగా అనిపిస్తే. ప్రసంగం: ప్రసంగంలో ఇబ్బందులు. అప్పుడు అంబులెన్స్‌కు కాల్ చేయాల్సిన సమయం వచ్చింది",
          "notification": "నోటిఫికేషన్",
          "noMove": "మీరు ఒక గంట నుండి కదలలేదు",
          "dailyWork": "పని చేయడానికి మీ రోజువారీ రిమైండర్",
          "waterBreak": "హే, ఇది నీటి విరామం కోసం సమయం",
          "locShared":
              "SOS! మీ అత్యవసర పరిచయానికి మీ స్థానం భాగస్వామ్యం చేయబడింది.",
          "profile": "ప్రొఫైల్",
          "edit": "సవరించు",
          "name": "సాయి కమల్",
          "save": "సేవ్ చేయండి",
          "height": "ఎత్తు",
          "weight": "బరువు",
          "age": "వయసు",
          "account": "ఖాతా",
          "data": "వ్యక్తిగత సమాచారం",
          "contacts": "అత్యవసర పరిచయాలు",
          "history": "కార్యాచరణ చరిత్ర",
          "remainders": "శేషాలను సెట్ చేయండి",
          "preferences": "ప్రాధాన్యతలు",
          "notification": "నోటిఫికేషన్",
          "language": "భాష",
          "languages": "ఆంగ్ల",
          "other": "ఇతర",
          "contactUs": "మమ్మల్ని సంప్రదించండి",
          "privacy": "గోప్యతా విధానం",
          "news": "వార్తలు",
          "tips": "కలిగి ఉండటానికి చిట్కాలు",
          "healthyHeart": "ఆరోగ్యకరమైన గుండె",
          "name": "M. పవన్ కుమార్",
          "mints": "నిమి చదవండి",
          "solution":
              "మా ప్రతిపాదిత పరిష్కారం ML మరియు ఫిట్‌నెస్ ట్రాకర్ల నుండి సేకరించిన డేటాను ఉపయోగించి హార్ట్ స్ట్రోక్‌ల ప్రమాదాన్ని అంచనా వేసే మొబైల్ యాప్. డేటా విశ్లేషణ ఆధారంగా హార్ట్ స్ట్రోక్‌ల ప్రమాదాన్ని తగ్గించడానికి యాప్ వినియోగదారులకు వ్యక్తిగతీకరించిన సిఫార్సులను అందిస్తుంది.",
        },
        'mr_IN': {
          "welcomeText": "Healthify मध्ये आपले स्वागत आहे.",
          "realTimePrediction":
              "मशीन लर्निंग आणि फिटनेस ट्रॅकर्स वापरून हृदयाघाताचा रिअल-टाइम अंदाज मिळवा.",
          "realTimeAlerts": "रिअल-टाइम सूचना",
          "healthy": "निरोगी राहा",
          "exploring": "अॅप एक्सप्लोर करा",
          "linkAccount":
              "तुमचे Google Fit/ Mi Fit खाते लिंक करा आणि रिअल-टाइम विश्लेषणे आणि अंदाज प्राप्त करणे सुरू करा.",
          "heartTips":
              "तुमचे हृदय सुरक्षित ठेवण्यासाठी ताज्या बातम्या आणि आरोग्य टिपा मिळवा.",
          "heartInfo":
              " तुमच्या दैनंदिन क्रियाकलापांचे तपशीलवार विश्लेषण आणि हृदयाशी संबंधित माहिती मिळवा.",
          "clickStartBtn": "सुरू ठेवण्यासाठी प्रारंभ करा वर क्लिक करा",
          "startedBtn": "सुरु करूया",
          "skipBtn": "वगळा",
          "nextBtn": "पुढे",
          "languageBtn_english": "इंग्रजी",
          "languageBtn_hindi": "हिंदी",
          "languageBtn_telugu": "तेलुगु",
          "languageBtn_gujarati": "गुजराती",
          "languageBtn_marathi": "मराठी",
          "healthify": "आरोग्यदायी",
          "whichOne": "तुम्ही कोणते?",
          "signIn": "साइन इन करा",
          "signUp": "साइन अप करा",
          "female": "स्त्री",
          "fullName": "पूर्ण नाव",
          "aboutYourSelf": "स्वत: बद्दल सांगा",
          "email": "पुरुष",
          "male": "पुरुष",
          "password": "पासवर्ड",
          "height": "उंची",
          "centimeter": "सेमी",
          "provide": "कृपया आपले प्रदान करा,",
          "cancel": "रद्द करा",
          "done": "झाले",
          "kilograms": "किलो",
          "emergency": "आपत्कालीन संपर्क:",
          "shareContact":
              "तुम्हाला तुमचा आणीबाणी संपर्क म्हणून ज्या लोकांची यादी करायची आहे त्यांचा संपर्क क्रमांक शेअर करा",
          "birthdy": "वाढदिवस",
          "forgetPassword": "पासवर्ड विसरलात? ",
          "contact": "संपर्क",
          "weight": "वजन",
          "register": "खाते नाही? नोंदणी करा",
          "loginIfHaveAccount": "आधीपासूनच एक खाते आहे? साइन इन करा",
          "next": "पुढे",
          "hello": "नमस्कार,",
          "increasedHeartRate": "वाढलेली हृदय गती. तू ठीक आहेस ना?",
          "daysAgo": "दिवसांपूर्वी",
          "heartRate": "हृदयाची गती",
          "exercise": "व्यायाम करा",
          "ExperiencingHeartStroke": "हार्ट स्ट्रोक अनुभवत आहात?",
          "bpm": "",
          "min": "मि",
          "yes": "होय",
          "no": "नाही",
          "sleep": "झोप",
          "calories": "कॅलरीज",
          " kcal": "",
          "tips": "निरोगी हृदयासाठी टिपा",
          "suddenHeartStroke":
              "असे झाल्यास काय करावे ते येथे आहेअचानक हार्ट स्ट्रोक",
          "name": "मिस्त्री पवन कुमार",
          "panBong": "पॅन बोंग",
          "analytics": "विश्लेषण",
          "bodyMass": "बॉडी मास इंडेक्स",
          "weight": "तुमचे वजन सामान्य आहे",
          "viewMore": "अधिक प i हा",
          "tracker": "हृदय गती ट्रॅकर",
          "weekly": "साप्ताहिक",
          "bodyWorkout": "अप्परबॉडी कसरत",
          "sunday": "रवि",
          "monday": "सोम",
          "tuesday": "मंगळ",
          "wednesday": "बुध",
          "thursday": "गुरु",
          "friday": "शुक्र",
          "saturday": "शनि",
          "countSteps": "पायऱ्या मोजल्या",
          "sleep": "झोप",
          "updates": "वास्तविक वेळ अद्यतने",
          "stacked": "रचलेला स्तंभ",
          "calories": "कॅलरीज",
          "activityProgress": "क्रियाकलाप प्रगती",
          "weekly": "साप्ताहिक",
          "stroke": "स्ट्रोक येत आहे?",
          "alert": "तुमच्या आणीबाणीच्या संपर्काला एक सूचना पाठवण्यात आली आहे",
          "callAmb": "रुग्णवाहिका कॉल करा",
          "whatToDo": "काय करायचं?",
          "waitAmb":
              "शांत राहा आणि रुग्णवाहिकेची वाट पहा.घाबरू नका. तुम्ही रुग्णवाहिका कॉल केली असल्यास, मदत येण्याची प्रतीक्षा करा. गाडी चालवण्याचा प्रयत्न करू नका.",
          "stayAwake":
              "देहभान हरवू नका जागृत राहण्याचा प्रयत्न करा. जर तुम्हाला वाटत असेल की तुम्ही भान गमावत आहात, तर एस्पिरिन घ्या. डोळे उघडे ठेवण्याचा प्रयत्न करा.",
          "cpr":
              "सीपीआरचे महत्त्व जर तुम्ही एकटे नसाल आणि तुम्हाला मदत करण्यासाठी कोणीतरी असेल, तर तुमचे जीवनावश्यक कमी होत असल्यास त्यांना CPR करण्यास सांगा.",
          "symprtoms":
              "लक्षणे तपासा:चेहरा: जर तुमचा चेहरा झुकत असेल. हात: जर तुमचे हात कमकुवत वाटत असतील. भाषण: बोलण्यात अडचणी. मग रुग्णवाहिका कॉल करण्याची वेळ आली आहे",
          "notification": "सूचना",
          "noMove": "एका तासापासून तू हलला नाहीस",
          "dailyWork": "काम करण्यासाठी तुमची रोजची आठवण",
          "waterBreak": "अहो, पाणी सोडण्याची वेळ आली आहे",
          "locShared":
              "SOS! तुमचे स्थान तुमच्या आपत्कालीन संपर्काशी शेअर केले गेले आहे.",
          "profile": "प्रोफ़ाइल",
          "edit": "संपादन करना",
          "name": "साईं कमल",
          "save": "बचाना",
          "height": "ऊंचाई",
          "weight": "वज़न",
          "age": "आयु",
          "account": "खाता",
          "data": "व्यक्तिगत डेटा",
          "contacts": "आपातकालीन संपर्क",
          "history": "गतिविधि इतिहास",
          "remainders": "अवशेष सेट करें",
          "preferences": "पसंद",
          "notification": "अधिसूचना",
          "language": "भाषा",
          "languages": "अंग्रेज़ी",
          "other": "अन्य",
          "contactUs": "संपर्क करें",
          "privacy": "गोपनीयता नीति",
          "news": "समाचार",
          "tips": "एक होने के लिए युक्तियाँ",
          "healthyHeart": "स्वस्थ दिल",
          "name": "M. Pavan Kumar",
          "mints": "मिनट पढ़ा",
          "solution":
              "हमारा प्रस्तावित समाधान एक मोबाइल ऐप है जो एमएल और फिटनेस ट्रैकर्स से एकत्र किए गए डेटा का उपयोग करके दिल के दौरे के जोखिम की भविष्यवाणी करता है। ऐप उपयोगकर्ताओं को डेटा विश्लेषण के आधार पर दिल के दौरे के जोखिम को कम करने के लिए व्यक्तिगत सिफारिशें प्रदान करेगा।",
        }
      };
}
